--- 

- name: 'Make sure kubelet service is running on worker nodes'
  systemd:
    name: kubelet
    enabled: true
    state: started
  become: true

- name: 'Copy join command from Ansiblehost to the worker nodes.'
  become: yes
  copy:
    src: /tmp/kubernetes_join_command
    dest: /tmp/kubernetes_join_command
    mode: 0777

- name: 'Join the Worker nodes to the cluster.'
  become: yes
  command: sudo sh /tmp/kubernetes_join_command
  register: joined_or_not


- name: 'Make sure kubelet service is running on worker nodes'
  systemd:
    name: kubelet
    enabled: true
    state: started
  become: true
